version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        read_only: false
        privileged: true
        expose:
          - "3000"
          - "9000"
        ports:
          - "3000:3000"
          - "9000:9000"
        tty: true
        entrypoint: ['bash']
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    mysql:
        build:
            context: ./
            dockerfile: docker/mysql.docker
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=artem"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=board"
        ports:
            - "3306:3306"
    redis:
        image: redis:3.0
        ports:
            - "6379:6379"
#    node:
#        image: node:9.11.1-alpine
#        volumes:
#            - ./:/var/www
#        working_dir: /var/www
#        tty: true